### ISSUE TITLE
Compilation failure with `simd_rem`

### ISSUE THREAD

**Issue by AdamNiederer** [rust-lang-nursery/stdsimd#201]
Hello,
stdsimd fails to build on my machine after 663cf64c9c2adaeec4ba704b8fe87d4667ebd3b9.

```
Adam, [21.11.17 00:49]
cargo build 
   Compiling stdsimd v0.0.3 (file:///home/adam/Programs/stdsimd)
error[E0441]: unrecognized platform-specific intrinsic function: simd_rem
  —> src/simd_llvm.rs:28:5
   |
28 |     pub fn simd_rem<T>(x: T, y: T) -> T;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile stdsimd.
```

I'm on an i3 5005u (+avx2). stdsimd compiles without issue on my 3570k (+avx). I'm using LLVM 5.0.0 on both, and changing the `target-cpu` has no effect on either machine.

**Comment by gnzlbg** [comment]
@AdamNiederer which Rust version do you have?

`simd_rem` requires a nightly that's newer than 16 days, and the AVX-512 intrinsics require a nightly newer than a couple of days.

**Comment by AdamNiederer** [comment]
Ah, such is life on the bleeding edge. Updating rustc fixed the issue; thanks.

**Comment by gnzlbg** [comment]
@AdamNiederer btw I added these intrinsics to `rustc` and `stdsimd` because I saw that you were using the vector types "operators" in `faster`. Since that commit, all useful operators should be implemented and working properly. If you miss any please ping me either here or in the rustc repo. Happy hacking!

**Comment by AdamNiederer** [comment]
Awesome, thank you! I'm trying to hack together the `gather` operators here so I can get a a proper stream swizzling API working in `faster` right now. I should have those ready to merge in a few days.
